cd "D:\KITE\KITE\ExternalLib\adb"
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
adb -s %1 shell input keyevent 25
